use clap::{Arg, Command};

pub fn build_cli() -> Command {
    Command::new("everything")
        .about("高速ファイル検索CLIツール")
        .version("0.1.0")
        .arg(
            Arg::new("query")
                .help("検索クエリ")
                .index(1)
                .required(false),
        )
        .arg(
            Arg::new("regex")
                .long("regex")
                .short('r')
                .help("正規表現検索を有効にする")
                .action(clap::ArgAction::SetTrue),
        )
        .arg(
            Arg::new("case-sensitive")
                .long("case-sensitive")
                .short('c')
                .help("大文字小文字を区別する")
                .action(clap::ArgAction::SetTrue),
        )
        .arg(
            Arg::new("update")
                .long("update")
                .short('u')
                .help("インデックスを更新する")
                .action(clap::ArgAction::SetTrue),
        )
        .arg(
            Arg::new("stats")
                .long("stats")
                .short('s')
                .help("統計情報を表示する")
                .action(clap::ArgAction::SetTrue),
        )
        .arg(
            Arg::new("watch")
                .long("watch")
                .short('w')
                .help("ファイル監視モードで起動する")
                .action(clap::ArgAction::SetTrue),
        )
        .arg(
            Arg::new("daemon")
                .long("daemon")
                .short('d')
                .help("デーモンモードで起動する（バックグラウンド監視）")
                .action(clap::ArgAction::SetTrue),
        )
        .arg(
            Arg::new("stop")
                .long("stop")
                .help("実行中のデーモンを停止する")
                .action(clap::ArgAction::SetTrue),
        )
        .arg(
            Arg::new("status")
                .long("status")
                .help("デーモンの状態を確認する")
                .action(clap::ArgAction::SetTrue),
        )
}